# Generated by Django 4.2.3 on 2023-07-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="publish_date",
            field=models.DateField(),
        ),
    ]
