# Generated by Django 4.2.3 on 2023-07-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_alter_newspaper_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
